food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('', views.index, name='index'),
    # /food/1 it this case link generate with item id.
    # path('<int:item_id>/',views.detail, name='detail'),
    path('<int:pk>/',views.FoodDetail.as_view(), name='detail'),
    # add item 
    # path('add/', views.create_item, name='create_item'),
    path('add/', views.CreateItem.as_view(), name='create_item'),
    # update  or edit
    path('update/<int:id>/',views.update_item, name='update_item'),
    # delete 
    path('delete/<int:id>/', views.delete_item, name='delete_item'),
    


]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from users import views as user_views
# django provide inbuild login and logout views so import 
from django.contrib.auth import views as authentication_views

from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name="register"),
     path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profilepage, name='profile'),
]

urlpatterns += [
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


users/urls.py
# from django.urls import path
# from . import views
# urlpatterns = [
#     path('', views.register, name="register")
# ]

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://png.pngtree.com/element_our/20200702/ourmid/pngtree-vector-illustration-knife-and-fork-western-food-plate-image_2283844.jpg")

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})
    

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self) :
        return self.user.username 

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    

    class Meta():
        model = User
        fields = ['username','first_name','last_name', 'email','password1','password2']

food/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse

from .forms import ItemForm
from .models import Item
from django.template import loader

# class based view import 
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.

def index(request):
    item_list = Item.objects.all()
    # template = loader.get_template('food/index.html')
    context = {
        'item_list':item_list,
    }
    # return HttpResponse(template.render(context,request))
    return render (request,'food/index.html',context)

# function based view 
# def detail(request, item_id):
#     # pk is primary key 
#     item = Item.objects.get(pk=item_id)
#     context= {
#         'item':item,
#     }
#     # return HttpResponse("This is item no/id: %s" % item_id)
#     return render(request,'food/detail.html',context)

# class based view 
class FoodDetail(DetailView):
    model = Item
    template_name= 'food/detail.html'



def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html',{'form': form})
# class based view for create item 
class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc', 'item_price','item_image']
    template_name = 'food/item-form.html'
    def form_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)



def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html',{'form':form, 'item':item})

def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method =='POST':
        item.delete()
        return redirect('food:index')
    return render(request, 'food/item_delete.html',{'item':item} )

users/views.py
from django.shortcuts import redirect, render
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created')
            return redirect ('login')
    else:
        form = RegisterForm()
    return render(request,'users/register.html',{'form':form})
@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} Base{% endblock %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href= {% static "food/style.css" %} >
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand p-3"> FoodApp</a>

        <div class="navbar">
            <a class="nav-item nav-link text-warning p-3" href="{% url 'food:index' %}"> View Item</a>
            {% if user.is_authenticated %}
            <a class="nav-item nav-link text-warning p-3" href="{% url 'food:create_item' %}"> Add Item</a>
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button class="nav-item nav-link text-warning p-3" type="submit">Logout</button>
                </form>
                <a class ="nav-item nav-link text-warning p-3" href="{% url 'profile' %}"> {{ user.username }}'s Profile </a>
                {% else %}
                    <a class="nav-item nav-link text-warning p-3" href="{% url 'login' %}"> Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
          </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
    
</body>
</html>

food/templates/food/detail.html
{% extends "food/base.html" %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %} {{ item.item_name }} {% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href= {% static "food/style.css" %} >
    </head>
    <body>
        {% block body %}

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <img src="{{item.item_image}}" alr="{{item.item_name}}" class="card" height="150px" width="100%" />
                </div>
                <div class="col-md-6">
                    <h3> {{ object.item_name }} </h3>
                    <h5> {{object.item_desc}} </h5>
                    <h6>$ {{object.item_price}} </h6>
                    <h6>Add this {{object.user_name}} </h6>
                    <a href={% url 'food:update_item' item.id %} type=button class="btn btn-success">Update </a>
                    <a href={% url 'food:delete_item' item.id %} type=button class="btn btn-success">Delete </a>
                </div>
            </div>
        </div>
        {% endblock body %}

    </body>
</html>

food/templates/food/index.html
{% extends "food/base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Food Item{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href= {% static "food/style.css" %} >
</head>
<body>
    
    {% block body %}

        {% for item in item_list %}
            <div class="row">
                <div class="col-md-3 offset-md-2">
                    <img class="card" height="150px" width="100%" src="{{item.item_image}}">
                </div>
                <div class="col-md-4">
                    <h3> {{ item.item_name }} </h3>
                    <h5> {{item.item_desc}} </h5>
                    <h6>$ {{item.item_price}} </h6>
                </div>
                <div class="col-md-2">
                    <a href="{% url 'food:detail' item.id %}" class="btn btn-success"> Details </a>
                </div>
            </div>
        {% endfor %}

    {% endblock %}

    {% comment %} old code 
    <ul>
        {% comment %} this url is hard coded url, which give manually. but we want to dynimic url  {% endcomment %}
        {% comment %} <a href="/food/{{ item.id }}"> <li> {{ item.item_name }}</li> {% endcomment %}
            {% comment %} this is dynamic url which defined with the url names  with namespace url {% endcomment %}
        {% comment %} <li>
            <a href="{% url 'food:detail' item.id %}"> {{ item.item_name }}
        </li>
            
    </ul> {% endcomment %}

</body>
</html>

food/templates/food/item-form.html
{% extends "food/base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Add Item{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href= {% static "food/style.css" %} >
</head>
<body>
    {% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4" >
                <div class="card">
                    <div class="card-header bg-warning text-black">
                        <div class="card_title">
                            <h2 class="text-center"> Add Items </h2>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name}}
                                    {{ field}}
                            {% endfor %}
                            <button type="submit"  class="btn btn-warning"> Add </button>
                        </form>
                    </div>
            </div>
        </div>
    </div>
    {% endblock body %}

    </body>
</html>

food/templates/food/item_delete.html
{% extends "food/base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Add Item{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href= {% static "food/style.css" %} >
</head>
<body>
    {% block body %}
    <div class=" position-absolute top-50 start-50 translate-middle">
        <form method="POST"> {% csrf_token %}
        <h2> Are You sure to delete {{ item.item_name}}</h2>
        {% comment %} <a  class="nav-item nav-link bg-primary p-3" href="{% url 'food:index' %}"><button type="button"> Home Page Click Hear</button></a> {% endcomment %}
        <button type='submit' class="btn btn-success" > Confirm</button>
        
        </form>
    </div>

    {% endblock body %}

    </body>
</html>

users/templates/users/l.html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <h1> logout page </h1>
    </body>
</html>

users/templates/users/login.html
{% extends "food/base.html" %}
<title> {% block title %} Login{% endblock %} </title>
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4" >
            <div class="card">
                <div class="card-header bg-warning text-black">
                    <div class="card_title">
                        <h2 class="text-center"> Login </h2>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name}}
                                {{ field}}
                        {% endfor %}
                        <button type="submit"  class="btn btn-warning"> Login </button>
                    </form>
                    <a class="text-warning p-3" href="{% url 'register' %}"> Register</a>
                </div>
        </div>
    </div>
</div>
{% endblock body %}

users/templates/users/logout.html
{% extends "food/base.html" %}
<!DOCTYPE html>
<html>
    <head>
        <title> {% block title %} Logout{% endblock %} </title>
    </head>
    <body>
        {% block body %}
        <div class="text-center">
            <h1> You Have beed logout </h1>
        <a class="text-center text-warning p-3" href="{% url 'login' %}"> Login</a>    </body>
        </div>
        
        {% endblock body %}

        
</html>

users/templates/users/profile.html
<h1> {{ user.username }} </h1>
<h1> {{ user.user_location }} </h1>
<img src="{{ user.profile.image.url }}" style="width: 200px; height:30%; ">
<a class="nav-item nav-link text-warning p-3" href="{% url 'food:index' %}"> Home page</a>

users/templates/users/register.html
{% extends "food/base.html" %}
<title> {% block title %} Register{% endblock %} </title>
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4" >
            <div class="card">
                <div class="card-header bg-warning text-black">
                    <div class="card_title">
                        <h2 class="text-center"> Register </h2>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST"> {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">

                                {{ field.name }}
                                <br>
                                {{ field }}
                        {% endfor %}
                        <button type="submit" class="btn btn-warning"> Sing Up</button>
                    </form>
                </div>
        </div>
    </div>
</div>

{% endblock body %}